// AUTO GENERATED BY JNIGEN 1.0.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `android.content.Context`
extension type Context._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/content/Context');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Context> type = $Context$Type$();
  static final _id_USB_SERVICE = _class.staticFieldId(
    r'USB_SERVICE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String USB_SERVICE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get USB_SERVICE =>
      _id_USB_SERVICE.getNullable(_class, jni$_.JString.type) as jni$_.JString?;
}

extension Context$$Methods on Context {
  static final _id_get$packageName = Context._class.instanceMethodId(
    r'getPackageName',
    r'()Ljava/lang/String;',
  );

  static final _get$packageName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract java.lang.String getPackageName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get packageName {
    final _$$selfRef = reference;
    return _get$packageName(
      _$$selfRef.pointer,
      _id_get$packageName.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_getSystemService = Context._class.instanceMethodId(
    r'getSystemService',
    r'(Ljava/lang/Class;)Ljava/lang/Object;',
  );

  static final _getSystemService =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final T getSystemService(java.lang.Class<T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getSystemService<$T extends jni$_.JObject?>(jni$_.JClass? class$) {
    final _$$selfRef = reference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getSystemService(
      _$$selfRef.pointer,
      _id_getSystemService.pointer,
      _$class$.pointer,
    ).object<$T?>();
  }

  static final _id_getSystemService$1 = Context._class.instanceMethodId(
    r'getSystemService',
    r'(Ljava/lang/String;)Ljava/lang/Object;',
  );

  static final _getSystemService$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.Object getSystemService(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSystemService$1(jni$_.JString? string) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getSystemService$1(
      _$$selfRef.pointer,
      _id_getSystemService$1.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }

  static final _id_startActivity = Context._class.instanceMethodId(
    r'startActivity',
    r'(Landroid/content/Intent;)V',
  );

  static final _startActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void startActivity(android.content.Intent intent)`
  void startActivity(Intent? intent) {
    final _$$selfRef = reference;
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    _startActivity(
      _$$selfRef.pointer,
      _id_startActivity.pointer,
      _$intent.pointer,
    ).check();
  }

  static final _id_startActivity$1 = Context._class.instanceMethodId(
    r'startActivity',
    r'(Landroid/content/Intent;Landroid/os/Bundle;)V',
  );

  static final _startActivity$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void startActivity(android.content.Intent intent, android.os.Bundle bundle)`
  void startActivity$1(Intent? intent, Bundle? bundle) {
    final _$$selfRef = reference;
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    _startActivity$1(
      _$$selfRef.pointer,
      _id_startActivity$1.pointer,
      _$intent.pointer,
      _$bundle.pointer,
    ).check();
  }
}

final class $Context$Type$ extends jni$_.JType<Context> {
  @jni$_.internal
  const $Context$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/Context;';
}

/// from: `android.content.Intent`
extension type Intent._(jni$_.JObject _$this)
    implements jni$_.JObject, Cloneable, Parcelable {
  static final _class = jni$_.JClass.forName(r'android/content/Intent');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Intent> type = $Intent$Type$();

  /// from: `static public final int FLAG_ACTIVITY_NEW_TASK`
  static const FLAG_ACTIVITY_NEW_TASK = 268435456;
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Intent() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer).object<Intent>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Landroid/content/Context;Ljava/lang/Class;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context, java.lang.Class<?> class)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Intent.new$1(Context? context, jni$_.JClass? class$) {
    final _$$classRef = _class.reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$context.pointer,
      _$class$.pointer,
    ).object<Intent>();
  }

  static final _id_new$2 = _class.constructorId(r'(Landroid/content/Intent;)V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Intent intent)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Intent.new$2(Intent? intent) {
    final _$$classRef = _class.reference;
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    return _new$2(
      _$$classRef.pointer,
      _id_new$2.pointer,
      _$intent.pointer,
    ).object<Intent>();
  }

  static final _id_new$3 = _class.constructorId(r'(Ljava/lang/String;)V');

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Intent.new$3(jni$_.JString? string) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _new$3(
      _$$classRef.pointer,
      _id_new$3.pointer,
      _$string.pointer,
    ).object<Intent>();
  }

  static final _id_new$4 = _class.constructorId(
    r'(Ljava/lang/String;Landroid/net/Uri;)V',
  );

  static final _new$4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string, android.net.Uri uri)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Intent.new$4(jni$_.JString? string, Uri? uri) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$uri = uri?.reference ?? jni$_.jNullReference;
    return _new$4(
      _$$classRef.pointer,
      _id_new$4.pointer,
      _$string.pointer,
      _$uri.pointer,
    ).object<Intent>();
  }

  static final _id_new$5 = _class.constructorId(
    r'(Ljava/lang/String;Landroid/net/Uri;Landroid/content/Context;Ljava/lang/Class;)V',
  );

  static final _new$5 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.String string, android.net.Uri uri, android.content.Context context, java.lang.Class<?> class)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Intent.new$5(
    jni$_.JString? string,
    Uri? uri,
    Context? context,
    jni$_.JClass? class$,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$uri = uri?.reference ?? jni$_.jNullReference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _new$5(
      _$$classRef.pointer,
      _id_new$5.pointer,
      _$string.pointer,
      _$uri.pointer,
      _$context.pointer,
      _$class$.pointer,
    ).object<Intent>();
  }
}

extension Intent$$Methods on Intent {
  static final _id_addFlags = Intent._class.instanceMethodId(
    r'addFlags',
    r'(I)Landroid/content/Intent;',
  );

  static final _addFlags =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.content.Intent addFlags(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  Intent? addFlags(core$_.int i) {
    final _$$selfRef = reference;
    return _addFlags(
      _$$selfRef.pointer,
      _id_addFlags.pointer,
      i,
    ).object<Intent?>();
  }

  static final _id_setData = Intent._class.instanceMethodId(
    r'setData',
    r'(Landroid/net/Uri;)Landroid/content/Intent;',
  );

  static final _setData =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.content.Intent setData(android.net.Uri uri)`
  /// The returned object must be released after use, by calling the [release] method.
  Intent? setData(Uri? uri) {
    final _$$selfRef = reference;
    final _$uri = uri?.reference ?? jni$_.jNullReference;
    return _setData(
      _$$selfRef.pointer,
      _id_setData.pointer,
      _$uri.pointer,
    ).object<Intent?>();
  }

  static final _id_setPackage = Intent._class.instanceMethodId(
    r'setPackage',
    r'(Ljava/lang/String;)Landroid/content/Intent;',
  );

  static final _setPackage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.content.Intent setPackage(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  Intent? setPackage(jni$_.JString? string) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _setPackage(
      _$$selfRef.pointer,
      _id_setPackage.pointer,
      _$string.pointer,
    ).object<Intent?>();
  }
}

final class $Intent$Type$ extends jni$_.JType<Intent> {
  @jni$_.internal
  const $Intent$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/Intent;';
}

/// from: `android.net.Uri`
extension type Uri._(jni$_.JObject _$this)
    implements jni$_.JObject, Comparable, Parcelable {
  static final _class = jni$_.JClass.forName(r'android/net/Uri');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Uri> type = $Uri$Type$();
  static final _id_fromParts = _class.staticMethodId(
    r'fromParts',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/net/Uri;',
  );

  static final _fromParts =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public android.net.Uri fromParts(java.lang.String string, java.lang.String string1, java.lang.String string2)`
  /// The returned object must be released after use, by calling the [release] method.
  static Uri? fromParts(
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
  ) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    return _fromParts(
      _$$classRef.pointer,
      _id_fromParts.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
    ).object<Uri?>();
  }
}

final class $Uri$Type$ extends jni$_.JType<Uri> {
  @jni$_.internal
  const $Uri$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/net/Uri;';
}

/// from: `android.app.PendingIntent`
extension type PendingIntent._(jni$_.JObject _$this)
    implements jni$_.JObject, Parcelable {
  static final _class = jni$_.JClass.forName(r'android/app/PendingIntent');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PendingIntent> type = $PendingIntent$Type$();

  /// from: `static public final int FLAG_MUTABLE`
  static const FLAG_MUTABLE = 33554432;

  /// from: `static public final int FLAG_UPDATE_CURRENT`
  static const FLAG_UPDATE_CURRENT = 134217728;
  static final _id_getBroadcast = _class.staticMethodId(
    r'getBroadcast',
    r'(Landroid/content/Context;ILandroid/content/Intent;I)Landroid/app/PendingIntent;',
  );

  static final _getBroadcast =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `static public android.app.PendingIntent getBroadcast(android.content.Context context, int i, android.content.Intent intent, int i1)`
  /// The returned object must be released after use, by calling the [release] method.
  static PendingIntent? getBroadcast(
    Context? context,
    core$_.int i,
    Intent? intent,
    core$_.int i1,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    return _getBroadcast(
      _$$classRef.pointer,
      _id_getBroadcast.pointer,
      _$context.pointer,
      i,
      _$intent.pointer,
      i1,
    ).object<PendingIntent?>();
  }
}

extension PendingIntent$$Methods on PendingIntent {
  static final _id_cancel = PendingIntent._class.instanceMethodId(
    r'cancel',
    r'()V',
  );

  static final _cancel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void cancel()`
  void cancel() {
    final _$$selfRef = reference;
    _cancel(_$$selfRef.pointer, _id_cancel.pointer).check();
  }
}

final class $PendingIntent$Type$ extends jni$_.JType<PendingIntent> {
  @jni$_.internal
  const $PendingIntent$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/app/PendingIntent;';
}

/// from: `android.hardware.usb.UsbManager`
extension type UsbManager._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/hardware/usb/UsbManager',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbManager> type = $UsbManager$Type$();
}

extension UsbManager$$Methods on UsbManager {
  static final _id_hasPermission = UsbManager._class.instanceMethodId(
    r'hasPermission',
    r'(Landroid/hardware/usb/UsbAccessory;)Z',
  );

  static final _hasPermission =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean hasPermission(android.hardware.usb.UsbAccessory usbAccessory)`
  core$_.bool hasPermission(UsbAccessory? usbAccessory) {
    final _$$selfRef = reference;
    final _$usbAccessory = usbAccessory?.reference ?? jni$_.jNullReference;
    return _hasPermission(
      _$$selfRef.pointer,
      _id_hasPermission.pointer,
      _$usbAccessory.pointer,
    ).boolean;
  }

  static final _id_hasPermission$1 = UsbManager._class.instanceMethodId(
    r'hasPermission',
    r'(Landroid/hardware/usb/UsbDevice;)Z',
  );

  static final _hasPermission$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean hasPermission(android.hardware.usb.UsbDevice usbDevice)`
  core$_.bool hasPermission$1(UsbDevice? usbDevice) {
    final _$$selfRef = reference;
    final _$usbDevice = usbDevice?.reference ?? jni$_.jNullReference;
    return _hasPermission$1(
      _$$selfRef.pointer,
      _id_hasPermission$1.pointer,
      _$usbDevice.pointer,
    ).boolean;
  }

  static final _id_openDevice = UsbManager._class.instanceMethodId(
    r'openDevice',
    r'(Landroid/hardware/usb/UsbDevice;)Landroid/hardware/usb/UsbDeviceConnection;',
  );

  static final _openDevice =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.hardware.usb.UsbDeviceConnection openDevice(android.hardware.usb.UsbDevice usbDevice)`
  /// The returned object must be released after use, by calling the [release] method.
  UsbDeviceConnection? openDevice(UsbDevice? usbDevice) {
    final _$$selfRef = reference;
    final _$usbDevice = usbDevice?.reference ?? jni$_.jNullReference;
    return _openDevice(
      _$$selfRef.pointer,
      _id_openDevice.pointer,
      _$usbDevice.pointer,
    ).object<UsbDeviceConnection?>();
  }

  static final _id_requestPermission = UsbManager._class.instanceMethodId(
    r'requestPermission',
    r'(Landroid/hardware/usb/UsbAccessory;Landroid/app/PendingIntent;)V',
  );

  static final _requestPermission =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void requestPermission(android.hardware.usb.UsbAccessory usbAccessory, android.app.PendingIntent pendingIntent)`
  void requestPermission(
    UsbAccessory? usbAccessory,
    PendingIntent? pendingIntent,
  ) {
    final _$$selfRef = reference;
    final _$usbAccessory = usbAccessory?.reference ?? jni$_.jNullReference;
    final _$pendingIntent = pendingIntent?.reference ?? jni$_.jNullReference;
    _requestPermission(
      _$$selfRef.pointer,
      _id_requestPermission.pointer,
      _$usbAccessory.pointer,
      _$pendingIntent.pointer,
    ).check();
  }

  static final _id_requestPermission$1 = UsbManager._class.instanceMethodId(
    r'requestPermission',
    r'(Landroid/hardware/usb/UsbDevice;Landroid/app/PendingIntent;)V',
  );

  static final _requestPermission$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void requestPermission(android.hardware.usb.UsbDevice usbDevice, android.app.PendingIntent pendingIntent)`
  void requestPermission$1(UsbDevice? usbDevice, PendingIntent? pendingIntent) {
    final _$$selfRef = reference;
    final _$usbDevice = usbDevice?.reference ?? jni$_.jNullReference;
    final _$pendingIntent = pendingIntent?.reference ?? jni$_.jNullReference;
    _requestPermission$1(
      _$$selfRef.pointer,
      _id_requestPermission$1.pointer,
      _$usbDevice.pointer,
      _$pendingIntent.pointer,
    ).check();
  }
}

final class $UsbManager$Type$ extends jni$_.JType<UsbManager> {
  @jni$_.internal
  const $UsbManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/hardware/usb/UsbManager;';
}

/// from: `android.hardware.usb.UsbDevice`
extension type UsbDevice._(jni$_.JObject _$this)
    implements jni$_.JObject, Parcelable {
  static final _class = jni$_.JClass.forName(r'android/hardware/usb/UsbDevice');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbDevice> type = $UsbDevice$Type$();
  static final _id_getDeviceName = _class.staticMethodId(
    r'getDeviceName',
    r'(I)Ljava/lang/String;',
  );

  static final _getDeviceName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public java.lang.String getDeviceName(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getDeviceName(core$_.int i) {
    final _$$classRef = _class.reference;
    return _getDeviceName(
      _$$classRef.pointer,
      _id_getDeviceName.pointer,
      i,
    ).object<jni$_.JString?>();
  }
}

extension UsbDevice$$Methods on UsbDevice {
  static final _id_get$deviceName = UsbDevice._class.instanceMethodId(
    r'getDeviceName',
    r'()Ljava/lang/String;',
  );

  static final _get$deviceName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getDeviceName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get deviceName {
    final _$$selfRef = reference;
    return _get$deviceName(
      _$$selfRef.pointer,
      _id_get$deviceName.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$manufacturerName = UsbDevice._class.instanceMethodId(
    r'getManufacturerName',
    r'()Ljava/lang/String;',
  );

  static final _get$manufacturerName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getManufacturerName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get manufacturerName {
    final _$$selfRef = reference;
    return _get$manufacturerName(
      _$$selfRef.pointer,
      _id_get$manufacturerName.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$productId = UsbDevice._class.instanceMethodId(
    r'getProductId',
    r'()I',
  );

  static final _get$productId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getProductId()`
  core$_.int get productId {
    final _$$selfRef = reference;
    return _get$productId(
      _$$selfRef.pointer,
      _id_get$productId.pointer,
    ).integer;
  }

  static final _id_get$productName = UsbDevice._class.instanceMethodId(
    r'getProductName',
    r'()Ljava/lang/String;',
  );

  static final _get$productName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getProductName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get productName {
    final _$$selfRef = reference;
    return _get$productName(
      _$$selfRef.pointer,
      _id_get$productName.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$vendorId = UsbDevice._class.instanceMethodId(
    r'getVendorId',
    r'()I',
  );

  static final _get$vendorId =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getVendorId()`
  core$_.int get vendorId {
    final _$$selfRef = reference;
    return _get$vendorId(_$$selfRef.pointer, _id_get$vendorId.pointer).integer;
  }
}

final class $UsbDevice$Type$ extends jni$_.JType<UsbDevice> {
  @jni$_.internal
  const $UsbDevice$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/hardware/usb/UsbDevice;';
}

/// from: `android.hardware.usb.UsbDeviceConnection`
extension type UsbDeviceConnection._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/hardware/usb/UsbDeviceConnection',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbDeviceConnection> type =
      $UsbDeviceConnection$Type$();
}

extension UsbDeviceConnection$$Methods on UsbDeviceConnection {
  static final _id_close = UsbDeviceConnection._class.instanceMethodId(
    r'close',
    r'()V',
  );

  static final _close =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void close()`
  void close() {
    final _$$selfRef = reference;
    _close(_$$selfRef.pointer, _id_close.pointer).check();
  }
}

final class $UsbDeviceConnection$Type$
    extends jni$_.JType<UsbDeviceConnection> {
  @jni$_.internal
  const $UsbDeviceConnection$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/hardware/usb/UsbDeviceConnection;';
}

/// from: `com.hoho.android.usbserial.driver.UsbSerialProber`
extension type UsbSerialProber._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/hoho/android/usbserial/driver/UsbSerialProber',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbSerialProber> type = $UsbSerialProber$Type$();
  static final _id_get$defaultProber = _class.staticMethodId(
    r'getDefaultProber',
    r'()Lcom/hoho/android/usbserial/driver/UsbSerialProber;',
  );

  static final _get$defaultProber =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public com.hoho.android.usbserial.driver.UsbSerialProber getDefaultProber()`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialProber? get defaultProber {
    final _$$classRef = _class.reference;
    return _get$defaultProber(
      _$$classRef.pointer,
      _id_get$defaultProber.pointer,
    ).object<UsbSerialProber?>();
  }
}

extension UsbSerialProber$$Methods on UsbSerialProber {
  static final _id_findAllDrivers = UsbSerialProber._class.instanceMethodId(
    r'findAllDrivers',
    r'(Landroid/hardware/usb/UsbManager;)Ljava/util/List;',
  );

  static final _findAllDrivers =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.List<com.hoho.android.usbserial.driver.UsbSerialDriver> findAllDrivers(android.hardware.usb.UsbManager usbManager)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<UsbSerialDriver?>? findAllDrivers(UsbManager? usbManager) {
    final _$$selfRef = reference;
    final _$usbManager = usbManager?.reference ?? jni$_.jNullReference;
    return _findAllDrivers(
      _$$selfRef.pointer,
      _id_findAllDrivers.pointer,
      _$usbManager.pointer,
    ).object<jni$_.JList<UsbSerialDriver?>?>();
  }
}

final class $UsbSerialProber$Type$ extends jni$_.JType<UsbSerialProber> {
  @jni$_.internal
  const $UsbSerialProber$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/hoho/android/usbserial/driver/UsbSerialProber;';
}

/// from: `com.hoho.android.usbserial.driver.UsbSerialDriver`
extension type UsbSerialDriver._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/hoho/android/usbserial/driver/UsbSerialDriver',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbSerialDriver> type = $UsbSerialDriver$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $UsbSerialDriver> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'getDevice()Landroid/hardware/usb/UsbDevice;') {
        final $r = _$impls[$p]!.getDevice();
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.$JObject$Type$())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
      if ($d == r'getPorts()Ljava/util/List;') {
        final $r = _$impls[$p]!.getPorts();
        return ($r as jni$_.JObject?)
                ?.as(const jni$_.$JObject$Type$())
                .reference
                .toPointer() ??
            jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $UsbSerialDriver $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.hoho.android.usbserial.driver.UsbSerialDriver',
      $p,
      _$invokePointer,
      [],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory UsbSerialDriver.implement($UsbSerialDriver $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<UsbSerialDriver>();
  }
}

extension UsbSerialDriver$$Methods on UsbSerialDriver {
  static final _id_getDevice = UsbSerialDriver._class.instanceMethodId(
    r'getDevice',
    r'()Landroid/hardware/usb/UsbDevice;',
  );

  static final _getDevice =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract android.hardware.usb.UsbDevice getDevice()`
  /// The returned object must be released after use, by calling the [release] method.
  UsbDevice? getDevice() {
    final _$$selfRef = reference;
    return _getDevice(
      _$$selfRef.pointer,
      _id_getDevice.pointer,
    ).object<UsbDevice?>();
  }

  static final _id_getPorts = UsbSerialDriver._class.instanceMethodId(
    r'getPorts',
    r'()Ljava/util/List;',
  );

  static final _getPorts =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract java.util.List<com.hoho.android.usbserial.driver.UsbSerialPort> getPorts()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<UsbSerialPort?>? getPorts() {
    final _$$selfRef = reference;
    return _getPorts(
      _$$selfRef.pointer,
      _id_getPorts.pointer,
    ).object<jni$_.JList<UsbSerialPort?>?>();
  }
}

abstract base mixin class $UsbSerialDriver {
  factory $UsbSerialDriver({
    required UsbDevice? Function() getDevice,
    required jni$_.JList<UsbSerialPort?>? Function() getPorts,
  }) = _$UsbSerialDriver;

  UsbDevice? getDevice();
  jni$_.JList<UsbSerialPort?>? getPorts();
}

final class _$UsbSerialDriver with $UsbSerialDriver {
  _$UsbSerialDriver({
    required UsbDevice? Function() getDevice,
    required jni$_.JList<UsbSerialPort?>? Function() getPorts,
  }) : _getDevice = getDevice,
       _getPorts = getPorts;

  final UsbDevice? Function() _getDevice;
  final jni$_.JList<UsbSerialPort?>? Function() _getPorts;

  UsbDevice? getDevice() {
    return _getDevice();
  }

  jni$_.JList<UsbSerialPort?>? getPorts() {
    return _getPorts();
  }
}

final class $UsbSerialDriver$Type$ extends jni$_.JType<UsbSerialDriver> {
  @jni$_.internal
  const $UsbSerialDriver$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/hoho/android/usbserial/driver/UsbSerialDriver;';
}

/// from: `com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl`
extension type UsbSerialPort$FlowControl._(jni$_.JObject _$this)
    implements Enum {
  static final _class = jni$_.JClass.forName(
    r'com/hoho/android/usbserial/driver/UsbSerialPort$FlowControl',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbSerialPort$FlowControl> type =
      $UsbSerialPort$FlowControl$Type$();
  static final _id_NONE = _class.staticFieldId(
    r'NONE',
    r'Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  /// from: `static public final com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl NONE`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialPort$FlowControl get NONE =>
      _id_NONE.get(_class, UsbSerialPort$FlowControl.type)
          as UsbSerialPort$FlowControl;

  static final _id_RTS_CTS = _class.staticFieldId(
    r'RTS_CTS',
    r'Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  /// from: `static public final com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl RTS_CTS`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialPort$FlowControl get RTS_CTS =>
      _id_RTS_CTS.get(_class, UsbSerialPort$FlowControl.type)
          as UsbSerialPort$FlowControl;

  static final _id_DTR_DSR = _class.staticFieldId(
    r'DTR_DSR',
    r'Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  /// from: `static public final com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl DTR_DSR`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialPort$FlowControl get DTR_DSR =>
      _id_DTR_DSR.get(_class, UsbSerialPort$FlowControl.type)
          as UsbSerialPort$FlowControl;

  static final _id_XON_XOFF = _class.staticFieldId(
    r'XON_XOFF',
    r'Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  /// from: `static public final com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl XON_XOFF`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialPort$FlowControl get XON_XOFF =>
      _id_XON_XOFF.get(_class, UsbSerialPort$FlowControl.type)
          as UsbSerialPort$FlowControl;

  static final _id_XON_XOFF_INLINE = _class.staticFieldId(
    r'XON_XOFF_INLINE',
    r'Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  /// from: `static public final com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl XON_XOFF_INLINE`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialPort$FlowControl get XON_XOFF_INLINE =>
      _id_XON_XOFF_INLINE.get(_class, UsbSerialPort$FlowControl.type)
          as UsbSerialPort$FlowControl;

  static final _id_values = _class.staticMethodId(
    r'values',
    r'()[Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl[] values()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<UsbSerialPort$FlowControl?>? values() {
    final _$$classRef = _class.reference;
    return _values(
      _$$classRef.pointer,
      _id_values.pointer,
    ).object<jni$_.JArray<UsbSerialPort$FlowControl?>?>();
  }

  static final _id_valueOf = _class.staticMethodId(
    r'valueOf',
    r'(Ljava/lang/String;)Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;',
  );

  static final _valueOf =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl valueOf(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static UsbSerialPort$FlowControl? valueOf(jni$_.JString? string) {
    final _$$classRef = _class.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _valueOf(
      _$$classRef.pointer,
      _id_valueOf.pointer,
      _$string.pointer,
    ).object<UsbSerialPort$FlowControl?>();
  }
}

final class $UsbSerialPort$FlowControl$Type$
    extends jni$_.JType<UsbSerialPort$FlowControl> {
  @jni$_.internal
  const $UsbSerialPort$FlowControl$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;';
}

/// from: `com.hoho.android.usbserial.driver.UsbSerialPort`
extension type UsbSerialPort._(jni$_.JObject _$this)
    implements jni$_.JObject, Closeable {
  static final _class = jni$_.JClass.forName(
    r'com/hoho/android/usbserial/driver/UsbSerialPort',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<UsbSerialPort> type = $UsbSerialPort$Type$();

  /// from: `static public final int PARITY_NONE`
  static const PARITY_NONE = 0;

  /// from: `static public final int PARITY_ODD`
  static const PARITY_ODD = 1;

  /// from: `static public final int PARITY_EVEN`
  static const PARITY_EVEN = 2;

  /// from: `static public final int PARITY_MARK`
  static const PARITY_MARK = 3;

  /// from: `static public final int PARITY_SPACE`
  static const PARITY_SPACE = 4;

  /// from: `static public final int STOPBITS_1`
  static const STOPBITS_1 = 1;

  /// from: `static public final int STOPBITS_1_5`
  static const STOPBITS_1_5 = 3;

  /// from: `static public final int STOPBITS_2`
  static const STOPBITS_2 = 2;

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $UsbSerialPort> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'getPortNumber()I') {
        final $r = _$impls[$p]!.getPortNumber();
        return $r.toJInteger().reference.toPointer();
      }
      if ($d == r'open(Landroid/hardware/usb/UsbDeviceConnection;)V') {
        _$impls[$p]!.open(($a![0] as UsbDeviceConnection?));
        return jni$_.nullptr;
      }
      if ($d == r'close()V') {
        _$impls[$p]!.close();
        return jni$_.nullptr;
      }
      if ($d == r'write([BI)V') {
        _$impls[$p]!.write(
          ($a![0] as jni$_.JByteArray?),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'write([BII)V') {
        _$impls[$p]!.write$1(
          ($a![0] as jni$_.JByteArray?),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![2] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'setParameters(IIII)V') {
        _$impls[$p]!.setParameters(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![2] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![3] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'setDTR(Z)V') {
        _$impls[$p]!.setDTR(
          ($a![0] as jni$_.JBoolean).toDartBool(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'setRTS(Z)V') {
        _$impls[$p]!.setRTS(
          ($a![0] as jni$_.JBoolean).toDartBool(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d ==
          r'setFlowControl(Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;)V') {
        _$impls[$p]!.setFlowControl(($a![0] as UsbSerialPort$FlowControl?));
        return jni$_.nullptr;
      }
      if ($d == r'isOpen()Z') {
        final $r = _$impls[$p]!.isOpen();
        return $r.toJBoolean().reference.toPointer();
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $UsbSerialPort $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.hoho.android.usbserial.driver.UsbSerialPort',
      $p,
      _$invokePointer,
      [
        if ($impl.open$async)
          r'open(Landroid/hardware/usb/UsbDeviceConnection;)V',
        if ($impl.close$async) r'close()V',
        if ($impl.write$async) r'write([BI)V',
        if ($impl.write$1$async) r'write([BII)V',
        if ($impl.setParameters$async) r'setParameters(IIII)V',
        if ($impl.setDTR$async) r'setDTR(Z)V',
        if ($impl.setRTS$async) r'setRTS(Z)V',
        if ($impl.setFlowControl$async) r'setFlowControl(Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory UsbSerialPort.implement($UsbSerialPort $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<UsbSerialPort>();
  }
}

extension UsbSerialPort$$Methods on UsbSerialPort {
  static final _id_getPortNumber = UsbSerialPort._class.instanceMethodId(
    r'getPortNumber',
    r'()I',
  );

  static final _getPortNumber =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract int getPortNumber()`
  core$_.int getPortNumber() {
    final _$$selfRef = reference;
    return _getPortNumber(
      _$$selfRef.pointer,
      _id_getPortNumber.pointer,
    ).integer;
  }

  static final _id_open = UsbSerialPort._class.instanceMethodId(
    r'open',
    r'(Landroid/hardware/usb/UsbDeviceConnection;)V',
  );

  static final _open =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void open(android.hardware.usb.UsbDeviceConnection usbDeviceConnection)`
  void open(UsbDeviceConnection? usbDeviceConnection) {
    final _$$selfRef = reference;
    final _$usbDeviceConnection =
        usbDeviceConnection?.reference ?? jni$_.jNullReference;
    _open(
      _$$selfRef.pointer,
      _id_open.pointer,
      _$usbDeviceConnection.pointer,
    ).check();
  }

  static final _id_close = UsbSerialPort._class.instanceMethodId(
    r'close',
    r'()V',
  );

  static final _close =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract void close()`
  void close() {
    final _$$selfRef = reference;
    _close(_$$selfRef.pointer, _id_close.pointer).check();
  }

  static final _id_write = UsbSerialPort._class.instanceMethodId(
    r'write',
    r'([BI)V',
  );

  static final _write =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public abstract void write(byte[] bs, int i)`
  void write(jni$_.JByteArray? bs, core$_.int i) {
    final _$$selfRef = reference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _write(_$$selfRef.pointer, _id_write.pointer, _$bs.pointer, i).check();
  }

  static final _id_write$1 = UsbSerialPort._class.instanceMethodId(
    r'write',
    r'([BII)V',
  );

  static final _write$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void write(byte[] bs, int i, int i1)`
  void write$1(jni$_.JByteArray? bs, core$_.int i, core$_.int i1) {
    final _$$selfRef = reference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _write$1(
      _$$selfRef.pointer,
      _id_write$1.pointer,
      _$bs.pointer,
      i,
      i1,
    ).check();
  }

  static final _id_setParameters = UsbSerialPort._class.instanceMethodId(
    r'setParameters',
    r'(IIII)V',
  );

  static final _setParameters =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Int32, jni$_.Int32, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void setParameters(int i, int i1, int i2, int i3)`
  void setParameters(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
    core$_.int i3,
  ) {
    final _$$selfRef = reference;
    _setParameters(
      _$$selfRef.pointer,
      _id_setParameters.pointer,
      i,
      i1,
      i2,
      i3,
    ).check();
  }

  static final _id_setDTR = UsbSerialPort._class.instanceMethodId(
    r'setDTR',
    r'(Z)V',
  );

  static final _setDTR =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public abstract void setDTR(boolean z)`
  void setDTR(core$_.bool z) {
    final _$$selfRef = reference;
    _setDTR(_$$selfRef.pointer, _id_setDTR.pointer, z ? 1 : 0).check();
  }

  static final _id_setRTS = UsbSerialPort._class.instanceMethodId(
    r'setRTS',
    r'(Z)V',
  );

  static final _setRTS =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public abstract void setRTS(boolean z)`
  void setRTS(core$_.bool z) {
    final _$$selfRef = reference;
    _setRTS(_$$selfRef.pointer, _id_setRTS.pointer, z ? 1 : 0).check();
  }

  static final _id_setFlowControl = UsbSerialPort._class.instanceMethodId(
    r'setFlowControl',
    r'(Lcom/hoho/android/usbserial/driver/UsbSerialPort$FlowControl;)V',
  );

  static final _setFlowControl =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void setFlowControl(com.hoho.android.usbserial.driver.UsbSerialPort$FlowControl flowControl)`
  void setFlowControl(UsbSerialPort$FlowControl? flowControl) {
    final _$$selfRef = reference;
    final _$flowControl = flowControl?.reference ?? jni$_.jNullReference;
    _setFlowControl(
      _$$selfRef.pointer,
      _id_setFlowControl.pointer,
      _$flowControl.pointer,
    ).check();
  }

  static final _id_isOpen = UsbSerialPort._class.instanceMethodId(
    r'isOpen',
    r'()Z',
  );

  static final _isOpen =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public abstract boolean isOpen()`
  core$_.bool isOpen() {
    final _$$selfRef = reference;
    return _isOpen(_$$selfRef.pointer, _id_isOpen.pointer).boolean;
  }
}

abstract base mixin class $UsbSerialPort {
  factory $UsbSerialPort({
    required core$_.int Function() getPortNumber,
    required void Function(UsbDeviceConnection? usbDeviceConnection) open,
    core$_.bool open$async,
    required void Function() close,
    core$_.bool close$async,
    required void Function(jni$_.JByteArray? bs, core$_.int i) write,
    core$_.bool write$async,
    required void Function(jni$_.JByteArray? bs, core$_.int i, core$_.int i1)
    write$1,
    core$_.bool write$1$async,
    required void Function(
      core$_.int i,
      core$_.int i1,
      core$_.int i2,
      core$_.int i3,
    )
    setParameters,
    core$_.bool setParameters$async,
    required void Function(core$_.bool z) setDTR,
    core$_.bool setDTR$async,
    required void Function(core$_.bool z) setRTS,
    core$_.bool setRTS$async,
    required void Function(UsbSerialPort$FlowControl? flowControl)
    setFlowControl,
    core$_.bool setFlowControl$async,
    required core$_.bool Function() isOpen,
  }) = _$UsbSerialPort;

  core$_.int getPortNumber();
  void open(UsbDeviceConnection? usbDeviceConnection);
  core$_.bool get open$async => false;
  void close();
  core$_.bool get close$async => false;
  void write(jni$_.JByteArray? bs, core$_.int i);
  core$_.bool get write$async => false;
  void write$1(jni$_.JByteArray? bs, core$_.int i, core$_.int i1);
  core$_.bool get write$1$async => false;
  void setParameters(core$_.int i, core$_.int i1, core$_.int i2, core$_.int i3);
  core$_.bool get setParameters$async => false;
  void setDTR(core$_.bool z);
  core$_.bool get setDTR$async => false;
  void setRTS(core$_.bool z);
  core$_.bool get setRTS$async => false;
  void setFlowControl(UsbSerialPort$FlowControl? flowControl);
  core$_.bool get setFlowControl$async => false;
  core$_.bool isOpen();
}

final class _$UsbSerialPort with $UsbSerialPort {
  _$UsbSerialPort({
    required core$_.int Function() getPortNumber,
    required void Function(UsbDeviceConnection? usbDeviceConnection) open,
    this.open$async = false,
    required void Function() close,
    this.close$async = false,
    required void Function(jni$_.JByteArray? bs, core$_.int i) write,
    this.write$async = false,
    required void Function(jni$_.JByteArray? bs, core$_.int i, core$_.int i1)
    write$1,
    this.write$1$async = false,
    required void Function(
      core$_.int i,
      core$_.int i1,
      core$_.int i2,
      core$_.int i3,
    )
    setParameters,
    this.setParameters$async = false,
    required void Function(core$_.bool z) setDTR,
    this.setDTR$async = false,
    required void Function(core$_.bool z) setRTS,
    this.setRTS$async = false,
    required void Function(UsbSerialPort$FlowControl? flowControl)
    setFlowControl,
    this.setFlowControl$async = false,
    required core$_.bool Function() isOpen,
  }) : _getPortNumber = getPortNumber,
       _open = open,
       _close = close,
       _write = write,
       _write$1 = write$1,
       _setParameters = setParameters,
       _setDTR = setDTR,
       _setRTS = setRTS,
       _setFlowControl = setFlowControl,
       _isOpen = isOpen;

  final core$_.int Function() _getPortNumber;
  final void Function(UsbDeviceConnection? usbDeviceConnection) _open;
  final core$_.bool open$async;
  final void Function() _close;
  final core$_.bool close$async;
  final void Function(jni$_.JByteArray? bs, core$_.int i) _write;
  final core$_.bool write$async;
  final void Function(jni$_.JByteArray? bs, core$_.int i, core$_.int i1)
  _write$1;
  final core$_.bool write$1$async;
  final void Function(core$_.int i, core$_.int i1, core$_.int i2, core$_.int i3)
  _setParameters;
  final core$_.bool setParameters$async;
  final void Function(core$_.bool z) _setDTR;
  final core$_.bool setDTR$async;
  final void Function(core$_.bool z) _setRTS;
  final core$_.bool setRTS$async;
  final void Function(UsbSerialPort$FlowControl? flowControl) _setFlowControl;
  final core$_.bool setFlowControl$async;
  final core$_.bool Function() _isOpen;

  core$_.int getPortNumber() {
    return _getPortNumber();
  }

  void open(UsbDeviceConnection? usbDeviceConnection) {
    return _open(usbDeviceConnection);
  }

  void close() {
    return _close();
  }

  void write(jni$_.JByteArray? bs, core$_.int i) {
    return _write(bs, i);
  }

  void write$1(jni$_.JByteArray? bs, core$_.int i, core$_.int i1) {
    return _write$1(bs, i, i1);
  }

  void setParameters(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
    core$_.int i3,
  ) {
    return _setParameters(i, i1, i2, i3);
  }

  void setDTR(core$_.bool z) {
    return _setDTR(z);
  }

  void setRTS(core$_.bool z) {
    return _setRTS(z);
  }

  void setFlowControl(UsbSerialPort$FlowControl? flowControl) {
    return _setFlowControl(flowControl);
  }

  core$_.bool isOpen() {
    return _isOpen();
  }
}

final class $UsbSerialPort$Type$ extends jni$_.JType<UsbSerialPort> {
  @jni$_.internal
  const $UsbSerialPort$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/hoho/android/usbserial/driver/UsbSerialPort;';
}

/// from: `com.hoho.android.usbserial.util.SerialInputOutputManager$Listener`
extension type SerialInputOutputManager$Listener._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/hoho/android/usbserial/util/SerialInputOutputManager$Listener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SerialInputOutputManager$Listener> type =
      $SerialInputOutputManager$Listener$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $SerialInputOutputManager$Listener>
  _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onNewData([B)V') {
        _$impls[$p]!.onNewData(($a![0] as jni$_.JByteArray?));
        return jni$_.nullptr;
      }
      if ($d == r'onRunError(Ljava/lang/Exception;)V') {
        _$impls[$p]!.onRunError(($a![0] as Exception?));
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $SerialInputOutputManager$Listener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.hoho.android.usbserial.util.SerialInputOutputManager$Listener',
      $p,
      _$invokePointer,
      [
        if ($impl.onNewData$async) r'onNewData([B)V',
        if ($impl.onRunError$async) r'onRunError(Ljava/lang/Exception;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory SerialInputOutputManager$Listener.implement(
    $SerialInputOutputManager$Listener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<SerialInputOutputManager$Listener>();
  }
}

extension SerialInputOutputManager$Listener$$Methods
    on SerialInputOutputManager$Listener {
  static final _id_onNewData = SerialInputOutputManager$Listener._class
      .instanceMethodId(r'onNewData', r'([B)V');

  static final _onNewData =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onNewData(byte[] bs)`
  void onNewData(jni$_.JByteArray? bs) {
    final _$$selfRef = reference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _onNewData(_$$selfRef.pointer, _id_onNewData.pointer, _$bs.pointer).check();
  }

  static final _id_onRunError = SerialInputOutputManager$Listener._class
      .instanceMethodId(r'onRunError', r'(Ljava/lang/Exception;)V');

  static final _onRunError =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract void onRunError(java.lang.Exception exception)`
  void onRunError(Exception? exception) {
    final _$$selfRef = reference;
    final _$exception = exception?.reference ?? jni$_.jNullReference;
    _onRunError(
      _$$selfRef.pointer,
      _id_onRunError.pointer,
      _$exception.pointer,
    ).check();
  }
}

abstract base mixin class $SerialInputOutputManager$Listener {
  factory $SerialInputOutputManager$Listener({
    required void Function(jni$_.JByteArray? bs) onNewData,
    core$_.bool onNewData$async,
    required void Function(Exception? exception) onRunError,
    core$_.bool onRunError$async,
  }) = _$SerialInputOutputManager$Listener;

  void onNewData(jni$_.JByteArray? bs);
  core$_.bool get onNewData$async => false;
  void onRunError(Exception? exception);
  core$_.bool get onRunError$async => false;
}

final class _$SerialInputOutputManager$Listener
    with $SerialInputOutputManager$Listener {
  _$SerialInputOutputManager$Listener({
    required void Function(jni$_.JByteArray? bs) onNewData,
    this.onNewData$async = false,
    required void Function(Exception? exception) onRunError,
    this.onRunError$async = false,
  }) : _onNewData = onNewData,
       _onRunError = onRunError;

  final void Function(jni$_.JByteArray? bs) _onNewData;
  final core$_.bool onNewData$async;
  final void Function(Exception? exception) _onRunError;
  final core$_.bool onRunError$async;

  void onNewData(jni$_.JByteArray? bs) {
    return _onNewData(bs);
  }

  void onRunError(Exception? exception) {
    return _onRunError(exception);
  }
}

final class $SerialInputOutputManager$Listener$Type$
    extends jni$_.JType<SerialInputOutputManager$Listener> {
  @jni$_.internal
  const $SerialInputOutputManager$Listener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/hoho/android/usbserial/util/SerialInputOutputManager$Listener;';
}

/// from: `com.hoho.android.usbserial.util.SerialInputOutputManager`
extension type SerialInputOutputManager._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/hoho/android/usbserial/util/SerialInputOutputManager',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SerialInputOutputManager> type =
      $SerialInputOutputManager$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lcom/hoho/android/usbserial/driver/UsbSerialPort;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.hoho.android.usbserial.driver.UsbSerialPort usbSerialPort)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SerialInputOutputManager(UsbSerialPort? usbSerialPort) {
    final _$$classRef = _class.reference;
    final _$usbSerialPort = usbSerialPort?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$usbSerialPort.pointer,
    ).object<SerialInputOutputManager>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Lcom/hoho/android/usbserial/driver/UsbSerialPort;Lcom/hoho/android/usbserial/util/SerialInputOutputManager$Listener;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.hoho.android.usbserial.driver.UsbSerialPort usbSerialPort, com.hoho.android.usbserial.util.SerialInputOutputManager$Listener listener)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SerialInputOutputManager.new$1(
    UsbSerialPort? usbSerialPort,
    SerialInputOutputManager$Listener? listener,
  ) {
    final _$$classRef = _class.reference;
    final _$usbSerialPort = usbSerialPort?.reference ?? jni$_.jNullReference;
    final _$listener = listener?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$usbSerialPort.pointer,
      _$listener.pointer,
    ).object<SerialInputOutputManager>();
  }
}

extension SerialInputOutputManager$$Methods on SerialInputOutputManager {
  static final _id_set$readTimeout = SerialInputOutputManager._class
      .instanceMethodId(r'setReadTimeout', r'(I)V');

  static final _set$readTimeout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setReadTimeout(int i)`
  set readTimeout(core$_.int i) {
    final _$$selfRef = reference;
    _set$readTimeout(
      _$$selfRef.pointer,
      _id_set$readTimeout.pointer,
      i,
    ).check();
  }

  static final _id_set$writeTimeout = SerialInputOutputManager._class
      .instanceMethodId(r'setWriteTimeout', r'(I)V');

  static final _set$writeTimeout =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setWriteTimeout(int i)`
  set writeTimeout(core$_.int i) {
    final _$$selfRef = reference;
    _set$writeTimeout(
      _$$selfRef.pointer,
      _id_set$writeTimeout.pointer,
      i,
    ).check();
  }

  static final _id_set$readBufferSize = SerialInputOutputManager._class
      .instanceMethodId(r'setReadBufferSize', r'(I)V');

  static final _set$readBufferSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void setReadBufferSize(int i)`
  set readBufferSize(core$_.int i) {
    final _$$selfRef = reference;
    _set$readBufferSize(
      _$$selfRef.pointer,
      _id_set$readBufferSize.pointer,
      i,
    ).check();
  }

  static final _id_writeAsync = SerialInputOutputManager._class
      .instanceMethodId(r'writeAsync', r'([B)V');

  static final _writeAsync =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void writeAsync(byte[] bs)`
  void writeAsync(jni$_.JByteArray? bs) {
    final _$$selfRef = reference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    _writeAsync(
      _$$selfRef.pointer,
      _id_writeAsync.pointer,
      _$bs.pointer,
    ).check();
  }

  static final _id_start = SerialInputOutputManager._class.instanceMethodId(
    r'start',
    r'()V',
  );

  static final _start =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void start()`
  void start() {
    final _$$selfRef = reference;
    _start(_$$selfRef.pointer, _id_start.pointer).check();
  }

  static final _id_stop = SerialInputOutputManager._class.instanceMethodId(
    r'stop',
    r'()V',
  );

  static final _stop =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void stop()`
  void stop() {
    final _$$selfRef = reference;
    _stop(_$$selfRef.pointer, _id_stop.pointer).check();
  }
}

final class $SerialInputOutputManager$Type$
    extends jni$_.JType<SerialInputOutputManager> {
  @jni$_.internal
  const $SerialInputOutputManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/hoho/android/usbserial/util/SerialInputOutputManager;';
}

/// from: `android.os.Build$VERSION`
extension type Build$VERSION._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/os/Build$VERSION');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION> type = $Build$VERSION$Type$();
  static final _id_SDK_INT = _class.staticFieldId(r'SDK_INT', r'I');

  /// from: `static public final int SDK_INT`
  static core$_.int get SDK_INT =>
      _id_SDK_INT.getNullable(_class, jni$_.jint.type) as core$_.int;
}

final class $Build$VERSION$Type$ extends jni$_.JType<Build$VERSION> {
  @jni$_.internal
  const $Build$VERSION$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION;';
}

/// from: `android.os.Bundle`
///
/// WARNING: Bundle is a stub. To generate bindings for this class, include
/// android.os.Bundle in your config's classes list.
///
extension type Bundle._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Bundle> type = $Bundle$Type$();
}

final class $Bundle$Type$ extends jni$_.JType<Bundle> {
  @jni$_.internal
  const $Bundle$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Bundle;';
}

/// from: `java.lang.Cloneable`
///
/// WARNING: Cloneable is a stub. To generate bindings for this class, include
/// java.lang.Cloneable in your config's classes list.
///
extension type Cloneable._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Cloneable> type = $Cloneable$Type$();
}

final class $Cloneable$Type$ extends jni$_.JType<Cloneable> {
  @jni$_.internal
  const $Cloneable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Cloneable;';
}

/// from: `android.os.Parcelable`
///
/// WARNING: Parcelable is a stub. To generate bindings for this class, include
/// android.os.Parcelable in your config's classes list.
///
extension type Parcelable._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Parcelable> type = $Parcelable$Type$();
}

final class $Parcelable$Type$ extends jni$_.JType<Parcelable> {
  @jni$_.internal
  const $Parcelable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Parcelable;';
}

/// from: `java.lang.Comparable`
///
/// WARNING: Comparable is a stub. To generate bindings for this class, include
/// java.lang.Comparable in your config's classes list.
///
extension type Comparable._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Comparable> type = $Comparable$Type$();
}

final class $Comparable$Type$ extends jni$_.JType<Comparable> {
  @jni$_.internal
  const $Comparable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Comparable;';
}

/// from: `java.lang.Exception`
///
/// WARNING: Exception is a stub. To generate bindings for this class, include
/// java.lang.Exception in your config's classes list.
///
extension type Exception._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Exception> type = $Exception$Type$();
}

final class $Exception$Type$ extends jni$_.JType<Exception> {
  @jni$_.internal
  const $Exception$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Exception;';
}

/// from: `android.hardware.usb.UsbAccessory`
///
/// WARNING: UsbAccessory is a stub. To generate bindings for this class, include
/// android.hardware.usb.UsbAccessory in your config's classes list.
///
extension type UsbAccessory._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<UsbAccessory> type = $UsbAccessory$Type$();
}

final class $UsbAccessory$Type$ extends jni$_.JType<UsbAccessory> {
  @jni$_.internal
  const $UsbAccessory$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/hardware/usb/UsbAccessory;';
}

/// from: `java.io.Closeable`
///
/// WARNING: Closeable is a stub. To generate bindings for this class, include
/// java.io.Closeable in your config's classes list.
///
extension type Closeable._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Closeable> type = $Closeable$Type$();
}

final class $Closeable$Type$ extends jni$_.JType<Closeable> {
  @jni$_.internal
  const $Closeable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/io/Closeable;';
}

/// from: `java.lang.Enum`
///
/// WARNING: Enum is a stub. To generate bindings for this class, include
/// java.lang.Enum in your config's classes list.
///
extension type Enum._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Enum> type = $Enum$Type$();
}

final class $Enum$Type$ extends jni$_.JType<Enum> {
  @jni$_.internal
  const $Enum$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/Enum;';
}
