name: uvc_camera_example
description: "Camera viewer example for uvc_camera."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.0

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  uvc_camera:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
